#!/usr/bin/env bash
#
# Embeds the built WebAssembly module into test/wasm_module.g.dart as base64
# so the browser runtime test (test/wasm_runtime_browser_test.dart) can run
# without a server. Run tool/build_wasm.sh first. The committed placeholder
# holds an empty string, which makes that test skip; this fills it in.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WASM="$ROOT/build/wasm/box3d_native.wasm"
OUT="$ROOT/test/wasm_module.g.dart"

if [ ! -f "$WASM" ]; then
  echo "Missing $WASM. Run tool/build_wasm.sh first." >&2
  exit 1
fi

{
  echo "// GENERATED by tool/embed_wasm.sh from the built wasm module. The"
  echo "// committed version holds an empty string; do not commit a filled one."
  echo "const String wasmModuleBase64 ="
  base64 -i "$WASM" | sed "s/.*/    '&'/"
  echo ";"
} > "$OUT"

echo "Embedded $(wc -c < "$WASM") bytes into $OUT"
